# -*- coding: utf-8 -*-
"""report_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ji59MZN952dV95RZvoYr_mccY4O-9rGU
"""

!pip install gensim scikit-learn pandas numpy

from sklearn.datasets import fetch_20newsgroups
import pandas as pd

# Load dataset
data = fetch_20newsgroups(subset='all')

df = pd.DataFrame({
    'text': data.data,
    'label': data.target
})

df.head()

df['text'] = df['text'].fillna("")
df['text'] = df['text'].str.lower()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['text'], df['label'], test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(stop_words='english', max_features=10000)

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english', max_features=10000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

from gensim.models import Word2Vec
import numpy as np

# Tokenize
sentences = [text.split() for text in X_train]

# Train model
w2v_model = Word2Vec(sentences, vector_size=100, window=5, min_count=2)

# Convert to vectors
def get_avg_vector(text):
    words = text.split()
    vectors = [w2v_model.wv[word] for word in words if word in w2v_model.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(100)

X_train_w2v = np.array([get_avg_vector(text) for text in X_train])
X_test_w2v = np.array([get_avg_vector(text) for text in X_test])

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

lr = LogisticRegression(max_iter=1000)
svm = LinearSVC()

from sklearn.metrics import accuracy_score, f1_score
import time

def run_model(X_train, X_test, y_train, y_test, model, name):
    start = time.time()

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    end = time.time()

    print(f"{name} | Accuracy: {accuracy_score(y_test, y_pred):.4f} | "
          f"F1 Score (macro): {f1_score(y_test, y_pred, average='macro'):.4f} | "
          f"Time: {end-start:.2f}s")

# BoW
run_model(X_train_bow, X_test_bow, y_train, y_test, lr, "BoW + LR")

# TF-IDF
run_model(X_train_tfidf, X_test_tfidf, y_train, y_test, lr, "TF-IDF + LR")

# Word2Vec
run_model(X_train_w2v, X_test_w2v, y_train, y_test, lr, "Word2Vec + LR")

# TF-IDF + SVM
run_model(X_train_tfidf, X_test_tfidf, y_train, y_test, svm, "TF-IDF + SVM")